build:
  nodes:
    tests:
      environment:
        php:
          version: 8.0.1
          compile_options: '--with-openssl --enable-sigchild --without-pear'

          pecl_extensions:
            - redis
  tests:
    override:
      -
        command: vendor/bin/phpunit --coverage-clover=build/clover.xml
        coverage:
          file: build/clover.xml
          format: php-clover

filter:
  excluded_paths:
    - "./tests"
